var map = L.map('map').setView([29.9, -97.75], 9);

var base_layer = L.tileLayer('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="http://cartodb.com/attributions">CartoDB</a>',
  subdomains: 'abcd',
  minZoom: 6,
  maxZoom: 14,
}).addTo(map);

var hispanic_tile =L.tileLayer('file:////Users/chrisessig/Documents/tribune/projects/redistricting/map/tiles/35-hispanic/{z}/{x}/{y}.png', {
  minZoom: 6,
  maxZoom: 14,
  tms: false,
  opacity: 1,
  attribution: 'Generated by QTiles'
}).addTo(map);

function getColor(d) {
  return 'red'
}

function getWeight(d) {
  if (parseInt(d) == 35) {
    return 5;
  } else {
    return 2;
  }
}

function styleCounties(feature) {
  return {
    fillColor: 'white',
    fillOpacity: 0,
    color: 'black',
    opacity: 1,
    weight: 0,
  };
}

function styleAll(feature) {
  return {
    fillColor: 'white',
    fillOpacity: 0,
    color: getColor(feature.properties["DIST_NBR"]),
    opacity: 1,
    weight: getWeight(feature.properties["DIST_NBR"]),
  };
}

geojson_counties = L.geoJSON(geo_counties, {
  style: styleCounties
}).addTo(map);

geojson_all_07_13 = L.geoJSON(geo_all_07_13, {
  style: styleAll
}).addTo(map);

geojson_all_current = L.geoJSON(geo_all_current, {
  style: styleAll
})

var cong_layers = {
  "2007 - 2013": geojson_all_07_13,
  "2013 - present": geojson_all_current
};

L.control.layers(cong_layers).addTo(map);

$("#hispanic_map_slider").slider({
  animate: true,
  value: 1,
  orientation: "vertical",
  min: 0,
  max: 1,
  step: 0.1,
  slide: function (event, ui) {
      hispanic_tile.setOpacity(ui.value);
  }
});

$('#hispanic_map_slider').mousedown(function(){
  map.dragging.disable();
})

$('#hispanic_map_slider').mouseup(function(){
  map.dragging.enable();
})